name: Build on Commit

on:
 - push

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar -Dsonar.projectKey=Netcracker_qubership-core-utils -Dsonar.organization=netcracker -Dsonar.host.url=https://sonarcloud.io"
            server-id: github
            java-version: 17
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
            sonar-token: ${{ secrets.SONAR_TOKEN }}